 version: "3"

 services:
    php:
        build: .
        container_name: DocWebox
        environment:
            - DB_HOST=db
            - DB_NAME=DocWeboxDB
            - DB_USERNAME=root
            - DB_PASSWORD=password
        ports:
            - '80:80'
        depends_on:
            - db


    db:
        image: mariadb
        container_name: DocWeboxDB
        environment:
            MARIADB_ROOT_PASSWORD: 'password'

    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin
        links:
            - db
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_USER: root
            PMA_PASSWORD: password
        ports:
            - "8080:80"

