 version: "3"

 services:
    php:
        build: .
        container_name: DocWebox
        environment:
            - DB_HOST=db
            - DB_NAME=DocWeboxDB
            - DB_USERNAME=root
            - DB_PASSWORD=changethispassword
        ports:
            - '80:80'
        depends_on:
            - db


    db:
        image: mariadb
        container_name: DocWeboxDB
        restart: always
        environment:
            MARIADB_ROOT_PASSWORD: 'changethispassword'

    adminer:
        image: adminer
        container_name: DocWeboxAdminer
        restart: always
        ports:
            - 8080:8080

